fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    epel: "git://github.com/jordiprats/eyp-epel.git"
  symlinks:
    nginx: "#{source_dir}"
